### ISSUE TITLE
Have error on mac, can you help ?

### ISSUE THREAD

**Issue by glitterinalarm** [NimaNzrii/comfyui-photoshop#17] opened 2024-05-06 15:43 UTC
Error occurred when executing ImageToMask:

True is not in list

File "/Users/xxxxxxxx/pinokio/api/comfyui.pinokio.git/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/Users/xxxxxxxx/pinokio/api/comfyui.pinokio.git/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/Users/xxxxxxxx/pinokio/api/comfyui.pinokio.git/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/Users/xxxxxxxx/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy_extras/nodes_mask.py", line 129, in image_to_mask
mask = image[:, :, :, channels.index(channel)]

**Comment by NimaNzrii** [comment] 2024-05-06 19:06
sorry i couldn't understand. you had problem on converting image to mask?

**Comment by NimaNzrii** [comment] 2024-05-07 13:27
So the problem is not from my node , but it seems some node in my workflow have some issues on mac device, i will install mac os tommorrow and fix it for you mate❤️

Until that, you can clear the workflow and test if **Photoshop to comfyui node** is working on empty workflow

**Comment by NimaNzrii** [comment] 2024-05-07 14:24
i will the main workflow for you tomorrow 🤗

**Comment by NimaNzrii** [comment] 2024-05-13 06:35
Sorry for my late reply 
This bug fixed but i forgot to tell you-_+

**Comment by glitterinalarm** [comment] 2024-05-13 14:47
!!! many thanks mate, you're the one !

**Comment by glitterinalarm** [comment] 2024-05-14 14:57
Hey Nima, how are you ? I try to use in photoshop (2024 on a mac) the Send to layers thing but nothing appears in the layers, do you know why ? Is there a shortcut ?

**Comment by NimaNzrii** [comment] 2024-07-15 15:23
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped

**Closed by NimaNzrii** 2024-07-15 15:23 UTC
