### ISSUE TITLE
module 'cv2' has no attribute 'resize'

### ISSUE THREAD

**Issue by schneegecko** [NimaNzrii/comfyui-photoshop#44] opened 2024-05-13 01:05 UTC
No matter what I do, I get the following error for CN Inline & CN scribble. Whats missing here?

Error occurred when executing AIO_Preprocessor:

module 'cv2' has no attribute 'resize'

File "H:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
return getattr(aux_class(), aux_class.FUNCTION)(**params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\scribble.py", line 37, in execute
return (common_annotator_call(model, image, resolution=resolution, thr_a=threshold), )
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 84, in common_annotator_call
np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\scribble\__init__.py", line 27, in __call__
input_image, remove_pad = resize_image_with_pad(input_image, detect_resolution, upscale_method)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "H:\sd\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 157, in resize_image_with_pad
img = cv2.resize(img, (W_target, H_target), interpolation=get_upscale_method(upscale_method) if k > 1 else cv2.INTER_AREA)
^^^^^^^^^^
![2024-05-13 03_01_31-ComfyUI - Brave](https://github.com/NimaNzrii/comfyui-photoshop/assets/55052469/a3aff646-cb97-408b-9518-af6952f820b0)
![2024-05-13 03_02_02-ComfyUI - Brave](https://github.com/NimaNzrii/comfyui-photoshop/assets/55052469/3bb3cabd-894c-45bc-b324-f913603420c4)

**Comment by schneegecko** [comment] 2024-05-13 01:17
![2024-05-13 03_16_30-ComfyUI – Mozilla Firefox](https://github.com/NimaNzrii/comfyui-photoshop/assets/55052469/4579bfde-576d-4391-9cbc-70c245364b7a)
could it be the aux preprocessors? However, I cant install it

**Comment by NimaNzrii** [comment] 2024-05-13 05:32
Yes the problem is from comfyui_controlnet_aux 

It's the first time I've seen someone with this bug

**Comment by schneegecko** [comment] 2024-05-13 06:10
> Yes the problem is from comfyui_controlnet_aux 
> 
> It's the first time I've seen someone with this bug

so what can I do?

**Comment by NimaNzrii** [comment] 2024-07-15 15:21
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped

**Closed by NimaNzrii** 2024-07-15 15:21 UTC
